name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Contentful Migration Example
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v1

      - name: Contentful Migration
        id: migrate
        uses: contentful-userland/contentful-migration-automation@v1
        with:
          delete_feature: false
          set_alias: true
          master_pattern: "prod-[DD]-[MM]-[YYYY]-[hh][mm][ss]"
          feature_pattern: "sandbox-[branch]"
          version_field: version
          version_content_type: versionTracking
          migrations_dir: contentful_migrations
          space_id: ${{ secrets.CONTENTFUL_SPACE_ID }}
          management_api_key: ${{ secrets.CONTENTFUL_MANAGEMENT_API_KEY }}
        env:
          LOG_LEVEL: verbose

      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            See changes to the [${{steps.migrate.outputs.environment_name }} ][1] Environment on Contentful.
            [1]: ${{steps.migrate.outputs.environment_url}}
