name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Restore dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -- --max-warnings 0

      - name: Type Checks
        run: npm run typecheck
